name: Build and publish Release

on:
  push:
    tags:
      - 'Release_v'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Package restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Prepare artifact
      run: mkdir -p ./output

    - name: Publish
      run: dotnet publish --configuration Release --output ./output --no-restore

    - name: Upload artifact
      uses: softprops/action-gh-release@1
      with:
        files: ./output/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
